name: flutter_demo
description: flutter_demo

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
#  qrscan: ^0.2.22
  dio: ^4.0.0
  keyboard_actions: ^3.4.0
  keyboard_avoider: ^0.1.2
  path_provider: ^2.0.1
  fluttertoast: ^8.0.3
  # 状态管理
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  flutter_bugly: ^0.3.1
  jpush_flutter: ^2.0.1
  flutter_easyrefresh: ^2.2.1
  # 启动URL 拨打电话等 https://pub.dev/packages/url_launcher
  url_launcher: ^6.0.8
  image_picker: ^0.8.2
  video_player: ^2.1.10
  photo_view: ^0.13.0
  image: ^3.1.3
  # listView 滚动指定item
  scrollable_positioned_list: ^0.2.3
  lpinyin: ^2.0.3
  flutter_lints: ^1.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - lib/widgets/
    - images/
